### ISSUE TITLE
getJwtToken defined twice; creates warnings in APIMatic.com

### ISSUE THREAD

**Issue by klauern** [cliffano/swaggy-jenkins#2]
Hello,

I'm looking at trying to find a spec for Jenkins, and it appears your implementation is closer than anything else I've found.  However, when I try to import your spec file into [APIMatic.com](https://apimatic.io/), it shows that `getJwtToken` is defined multiple times:

![image](https://user-images.githubusercontent.com/4735/29575665-d41200b0-872a-11e7-90c2-9007b47306d1.png)

**Comment by klauern** [comment]
I'm not sure if this is worthy of a subsequent issue, but there is also this that happens after clicking "Proceed":

![image](https://user-images.githubusercontent.com/4735/29576508-c2bff260-872d-11e7-95d5-0fb43709066f.png)

**Comment by cliffano** [comment]
@klauern Thanks for notifying me about the above.
- I've renamed `getJwtToken` duplication to `getJsonWebToken` and `getJsonWebKey`
  JWT support is currently a quick workaround (i.e. add `Bearer: ` prefix to the value), it will use built-in support when I upgraded the spec to OpenAPI 3.0
- I've raised a separate issue to deal with field names that are too long https://github.com/cliffano/swaggy-jenkins-cli/issues/1 . Once it's fixed there, it will be part of the definitions generation process to trim package value from field name.
- Re missing description field, this will stay missing for all of the generated definitions because the information is not available from the response JSONs that Jenkins produced. Unfortunately this can only be fixed if there's someone who's willing to go through the 1000+ lines of generated definitions, or if Jenkins produces an OpenAPI spec as the source of truth in the first place, that would be the right spot to write the descriptions one by one.

Do you mind pointing me to other Jenkins OpenAPI spec efforts? Google failed me before I started writing mine, so I started from scratch and ended up with the approach of generating definitions from response JSONs. So I'm curious how others built such spec.

I also noticed that you contributed to `bndr/gojenkins` , do you reckon it could use https://github.com/cliffano/swaggy-jenkins/tree/master/clients/go/generated ?

**Comment by klauern** [comment]
Outstanding!

I have only been perusing the information to try to formalize a document on Jenkins.  I too find it frustrating that there's no formal API for the interface, so I was pleasantly surprised to see such a thorough effort on your part.  I can't think of any other OpenAPI spec efforts being done on this, however.  I found your repo through the Jenkins JIRA ticket, so outside of that, there's not a whole lot.

Referencing the [gojenkins](https://github.com/bndr/gojenkins) repo, I don't know if it will be flexible to even attempt to integrate your work with it.  That said, there's another tool called [goswagger](https://goswagger.io/) that can generate full client API's from Swagger docs, so I would think that you could generate a client using that a lot easier than trying to retrofit the `gojenkins` work.  To be honest, the API they wrote is lacking in a lot of ways, and some of it just looks like copypasta from the Python PIP around Jenkins, so I don't know if it's a very close resemblance to a Go HTTP client API, moreso a reimplementation of the Python Jenkins API in Go.

**Comment by cliffano** [comment]
I'm going to close this ticket since the duplication has been fixed in master. However, please feel free to resume the discussion.

For generating the client APIs, I'm sticking with `swagger-codegen` since it's the true source and new language support will be added to that project first before `goswagger`.
As for `gojenkins` and any other Jenkins client implementations, the value of using the generated clients would be on reducing boilerplate code in dealing with request, response, authentication, etc. So a client implementation code base can be greatly reduced. I reckon the clients which implement beyond API calls, e.g. stream console output, would still need to exist. However, those who simply implement the request sending can easily be replaced by the generated code.
